# Generated by Django 3.2.12 on 2023-03-05 12:57

import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='bike',
            name='size',
            field=models.CharField(choices=[('', 'Select bike size.'), ('S', 'small'), ('M', 'medium'), ('L', 'large')], default='', max_length=1, validators=[application.validators.bikeSizeValidator]),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='start_time',
            field=models.DateTimeField(help_text='Leave blank for current time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='preferred name'),
        ),
    ]
