# Generated by Django 3.2.12 on 2023-03-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20230305_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('own_bike', 'Can be a bike steward')]},
        ),
    ]
