# Generated by Django 3.2.12 on 2023-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='key_received',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='key_returned',
            field=models.BooleanField(null=True),
        ),
    ]
