# Generated by Django 3.2.12 on 2023-03-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20230305_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.issue'),
        ),
    ]
